### ISSUE TITLE
ค่าศาสนา มีให้อ่านไหมครับ ลองแล้วไม่เจอครับ

### ISSUE THREAD

**Issue by ibee133** [chakphanu/ThaiNationalIDCard#5]
ค่าศาสนา มีให้อ่านไหมครับ ลองแล้วไม่เจอครับ

**Comment by chakphanu** [comment]
ไม่มีครับ เพราะเป็นข้อมูลที่ไม่ได้บังคับในบัตรประชาชนครับ
ทาง กระทรวงมหาดไทยเลยไม่บรรจุลงใน chip ครับ
