### ISSUE TITLE
ดึงรูป ไปวางที่picturebox ทำไงครับ

### ISSUE THREAD

**Issue by tuidento** [chakphanu/ThaiNationalIDCard#9]

**Comment by prakasitlasree** [comment]
picture มันได้ออกมาเป็น binary อยู่แล้ว คุณก็แปลง binary to image แล้วก็เอาไปใส่ใน image control ตามปกติไงครับ

**Comment by tuidento** [comment]
ขอบคุณครับ เจอแล้วครับ ต้องใช้readallpicture()
